name: firecrown-docs
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python>=3.8
  - cosmosis
  - cosmosis-build-standard-library
  - flake8
  - mypy
  - numpy>=1.16
  - quarto
  - plantuml
  - pip
  - pyccl>=2.0
  - pytest
  - sacc>=0.3
  - scipy
  - sphinx
  - sphinx-autoapi
  - sphinx-autodoc-typehints
  - sphinxcontrib-apidoc
  - sphinx_rtd_theme
  - pip>=20.1  # pip is needed as dependency
  - pip:
    - autoclasstoc
    - cobaya
